---
# Source: submarine/templates/submarine-ingress.yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: submarine-server-ingress

spec:
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: submarine-server
              servicePort: 8080
