# permissions for end users to view submarines.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: submarine-viewer-role
rules:
- apiGroups:
  - submarine.apache.org
  resources:
  - submarines
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - submarine.apache.org
  resources:
  - submarines/status
  verbs:
  - get
